### PR TITLE
v1.1.1; switch to github for sdist

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@djsutherland @synapticarbors The bot failed to pick up v1.1.1 because the sdist was only on github. Review and merge appreciated!

**Comment by synapticarbors** [comment]
Could you do two things:
1. add a `pip check` to the tests
2. update the `conda-forge.yml` to include:

```
bot:
  automerge: false
  inspection: update-grayskull
```

Everything else looks good and I'm happy to merge after. Also thanks for catching this an offering to be a co-maintainer.

**Comment by thewchan** [comment]
@synapticarbors Done!

**Pull request merged**
