### PR TITLE
back-release 0.9.2

### PR DESCRIPTION
**Pull request by carlodri**
⚠️ **MERGE INTO `back-release-0.9.2` branch, not `master`** ⚠️ 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Required to unblock https://github.com/conda-forge/databases-feedstock/pull/21

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge/pymysql can someone please merge into an appropriate branch?

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
@conda-forge/core -- what's the procedure for publishing an older version of a package that's missing like is the case here? I didn't see a recommended procedure list in the docs.

**Comment by beckermr** [comment]
Make a new branch on the feedstock with whatever name you'd like. (It appears the PR author suggested something here). Then merge this PR into that branch.

**Comment by carlodri** [comment]
@synapticarbors yes, as @beckermr says, AFAIR you should merge into a separate branch as I suggested in the PR

**Pull request merged**
